In [1]:
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.metrics import accuracy_score,confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import make_classification
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
import pandas as pd
import numpy as np
import warnings
import pickle
import os
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px


warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.feature_selection import RFE

In [3]:
description= pd.read_csv('archive/description.csv')
diets= pd.read_csv('archive/diets.csv')

medications= pd.read_csv('archive/medications.csv')
precautions= pd.read_csv('archive/precautions_df.csv', index_col= 0)
Symptom_severity_df= pd.read_csv('archive/Symptom-severity.csv')

sym_des= pd.read_csv('archive/symtoms_df.csv', index_col= 0)


df= pd.read_csv('archive/Training.csv')
workout=pd.read_csv('archive/workout_df.csv').iloc[:, 2:]

sym_des

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN
...,...,...,...,...,...
4915,(vertigo) Paroymsal Positional Vertigo,vomiting,headache,nausea,spinning_movements
4916,Acne,skin_rash,pus_filled_pimples,blackheads,scurring
4917,Urinary tract infection,burning_micturition,bladder_discomfort,foul_smell_of urine,continuous_feel_of_urine
4918,Psoriasis,skin_rash,joint_pain,skin_peeling,silver_like_dusting
4919,Impetigo,skin_rash,high_fever,blister,red_sore_around_nose

In [4]:
# Eliminating all NaN from the dataset

sym_des.dropna(inplace= True)
precautions.dropna(inplace= True)

print("precautions Dataframe\n", precautions.isna().sum())
print("\nSymptons Dataframe\n", sym_des.isna().sum())

precautions Dataframe
 Disease         0
Precaution_1    0
Precaution_2    0
Precaution_3    0
Precaution_4    0
dtype: int64

Symptons Dataframe
 Disease      0
Symptom_1    0
Symptom_2    0
Symptom_3    0
Symptom_4    0
dtype: int64

In [5]:
#DataFrames
df_sym_des = pd.DataFrame(sym_des)
df_df = pd.DataFrame(df)

In [6]:
df_sym_des.describe()

#min/max
#count and count uniques 
#average 
#outliers
#Description 
#Mean/Mode

            Disease  Symptom_1  Symptom_2 Symptom_3    Symptom_4
count          4572       4572       4572      4572         4572
unique           41         28         42        46           50
top     Hepatitis B   vomiting   vomiting   fatigue   high_fever
freq            120        732        870       726          378

In [7]:
most_frequent_disease = df_sym_des['Disease'].value_counts()
most_frequent_symptom1 = df_sym_des['Symptom_1'].value_counts()
most_frequent_symptom2 = df_sym_des['Symptom_2'].value_counts()
most_frequent_symptom3 = df_sym_des['Symptom_3'].value_counts()
most_frequent_symptom4 = df_sym_des['Symptom_4'].value_counts()

In [8]:
# Most Frequent Diseases
df_mfd = pd.DataFrame(most_frequent_disease)
df_mfd = df_mfd.reset_index()


fig = px.treemap(df_mfd, path=[px.Constant("all"), 'Disease'], values= 'count')

fig.update_traces(root_color="lightgray")
fig.update_layout(margin = dict(t=50, l=25, r=25, b=25))
fig.show()

In [9]:
# Most Frequent Symptom_1
df_mfs1 = pd.DataFrame(most_frequent_symptom1)
df_mfs1 = df_mfs1.reset_index()

fig = px.treemap(df_mfs1, path=[px.Constant("all"), 'Symptom_1'], values= 'count')

fig.update_traces(root_color="lightgray")
fig.update_layout(margin = dict(t=50, l=25, r=25, b=25))
fig.show()

In [10]:
# Most Frequent Symptom_2
df_mfs2 = pd.DataFrame(most_frequent_symptom2)
df_mfs2 = df_mfs2.reset_index()

fig = px.treemap(df_mfs2, path=[px.Constant("all"), 'Symptom_2'], values= 'count')

fig.update_traces(root_color="lightgray")
fig.update_layout(margin = dict(t=50, l=25, r=25, b=25))
fig.show()

In [11]:
# Most Frequent Symptom_3
df_mfs3 = pd.DataFrame(most_frequent_symptom3)
df_mfs3 = df_mfs3.reset_index()

fig = px.treemap(df_mfs3, path=[px.Constant("all"), 'Symptom_3'], values= 'count')

fig.update_traces(root_color="lightgray")
fig.update_layout(margin = dict(t=50, l=25, r=25, b=25))
fig.show()

In [12]:
# Most Frequent Symptom_4
df_mfs4 = pd.DataFrame(most_frequent_symptom4)
df_mfs4 = df_mfs4.reset_index()

fig = px.treemap(df_mfs4, path=[px.Constant("all"), 'Symptom_4'], values= 'count')

fig.update_traces(root_color="lightgray")
fig.update_layout(margin = dict(t=50, l=25, r=25, b=25))
fig.show()

In [13]:
stats = df_df.describe().transpose()
stats.reset_index(inplace= True)
stats.columns = ['Symptoms', 'count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']
stats

                 Symptoms   count      mean       std  min  25%  50%  75%  max
0                 itching  4920.0  0.137805  0.344730  0.0  0.0  0.0  0.0  1.0
1               skin_rash  4920.0  0.159756  0.366417  0.0  0.0  0.0  0.0  1.0
2    nodal_skin_eruptions  4920.0  0.021951  0.146539  0.0  0.0  0.0  0.0  1.0
3     continuous_sneezing  4920.0  0.045122  0.207593  0.0  0.0  0.0  0.0  1.0
4               shivering  4920.0  0.021951  0.146539  0.0  0.0  0.0  0.0  1.0
..                    ...     ...       ...       ...  ...  ...  ...  ...  ...
127  small_dents_in_nails  4920.0  0.023171  0.150461  0.0  0.0  0.0  0.0  1.0
128    inflammatory_nails  4920.0  0.023171  0.150461  0.0  0.0  0.0  0.0  1.0
129               blister  4920.0  0.023171  0.150461  0.0  0.0  0.0  0.0  1.0
130  red_sore_around_nose  4920.0  0.023171  0.150461  0.0  0.0  0.0  0.0  1.0
131     yellow_crust_ooze  4920.0  0.023171  0.150461  0.0  0.0  0.0  0.0  1.0

[132 rows x 9 columns]

In [14]:
# sys_des. How often does each disease occur and often each often symptons occur.
# df optional

fig = px.treemap(stats, path=[px.Constant("all"), 'Symptoms'], values= 'mean')

fig.update_traces(root_color="lightgray")
fig.update_layout(margin = dict(t=50, l=25, r=25, b=25))
fig.show()